<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panel [
 <!ELEMENT panel (nombre, vuelo+, fecha)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT vuelo (diario?,origen,destino,hora_salida,hora_llegada)>
 <!ATTLIST vuelo codigo ID #REQUIRED>
 <!ATTLIST vuelo estado (C | E | R) "E">
 <!ELEMENT diario EMPTY>
 <!ELEMENT origen (#PCDATA)>
 <!ELEMENT destino (#PCDATA)>
 <!ELEMENT hora_salida (#PCDATA)>
 <!ELEMENT hora_llegada (#PCDATA)>
 <!ELEMENT fecha (#PCDATA)>
 ]>
<panel>
    <nombre>Aeropuerto JFK</nombre>
    <vuelo codigo="v22" estado="R">
        <diario/>
        <origen>new York</origen>
        <destino>Chicago</destino>
        <hora_salida>9:30</hora_salida>
        <hora_llegada>11:30</hora_llegada>
    </vuelo>
    <vuelo codigo="v23" estado="C">
        <origen>New York</origen>
        <destino>Miami</destino>
        <hora_salida>10:15</hora_salida>
        <hora_llegada>11:15</hora_llegada>
    </vuelo>
    <fecha>20/12/2013</fecha>
</panel>